exchangerate:
  exchangerate_api_key: '63c8615fa4e2bd6573fb3a51'
  exchangerate_api_url: 'https://v6.exchangerate-api.com/v6/'
  base_currency_code: 'usd'
tinkoff:
  api_url: # Tinkoff api url
  terminal_key: # Tinkoff terminal key
  password: # Tinkoff password
  test_card_number: # Tinkoff test card number
  test_card_cvc: # Tinkoff test card CVC
  test_card_exp_date: # Tinkoff test card expiration date
storage:
  host: "localhost"
  port: "5432"
  dbname: "quest_holder"
  username: "postgres"
  password: "root"
  ssl: "disable"
redis:
  addr: "127.0.0.1" # Redis server address, typically 'localhost' or a remote server IP
  username: "" # Username for the Redis server (if required)
  password: "" # Password for the Redis server (if required)
  port: "6379" # Redis server port, default is 6379
secure_params:
  jwt_secret: "test"
  salt: "test"
  session_token_hours_life: 8
  admin_session_token_hours_life: 72
  temporary_password_life_minute: 5
vk_api:
  client_id: "bZUSYsKKHKnXBaKk9OwX"
  client_secret: "54ab0e8854ab0e8854ab0e887d5789e996554ab54ab0e883382ed168307b3c38b675d7c"
  redirect_uri: ""
firebase:
  credentials_server_token: ""
ali_cloud_oss_storage:
  key: ""
  secret: ""
  bucket: ""
  endpoint: ""
smtp_mail_server:
  base_mail: "questholder@yandex.ru"
  base_title: "Quest Holder"
  smtp_password: "xurdwrobvybmquxl"
  smtp_host: "smtp.yandex.ru"
  smtp_port: "587" # 465 for SSL or 587 for localhost
server:
  rest_admin_service: # Admin service address
    bind: '0.0.0.0'
    port: 10001
  notifications_service:
    bind: '0.0.0.0'
    internal: '0.0.0.0'
    port: 10002
  rest_user_service: # User API service address
    bind: '0.0.0.0'
    port: 10005
  user_service: # User API service address
    bind: '0.0.0.0'
    internal: '0.0.0.0'
    port: 10006