// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: messages/DetectorIPStruct.proto

package protoobj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectorIPStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP            *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	IsINBlackList *wrapperspb.BoolValue   `protobuf:"bytes,2,opt,name=IsINBlackList,proto3" json:"IsINBlackList,omitempty"`
	RegionInfo    *RegionInfoDetected     `protobuf:"bytes,3,opt,name=RegionInfo,proto3" json:"RegionInfo,omitempty"`
}

func (x *DetectorIPStruct) Reset() {
	*x = DetectorIPStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_DetectorIPStruct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectorIPStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorIPStruct) ProtoMessage() {}

func (x *DetectorIPStruct) ProtoReflect() protoreflect.Message {
	mi := &file_messages_DetectorIPStruct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorIPStruct.ProtoReflect.Descriptor instead.
func (*DetectorIPStruct) Descriptor() ([]byte, []int) {
	return file_messages_DetectorIPStruct_proto_rawDescGZIP(), []int{0}
}

func (x *DetectorIPStruct) GetIP() *wrapperspb.StringValue {
	if x != nil {
		return x.IP
	}
	return nil
}

func (x *DetectorIPStruct) GetIsINBlackList() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsINBlackList
	}
	return nil
}

func (x *DetectorIPStruct) GetRegionInfo() *RegionInfoDetected {
	if x != nil {
		return x.RegionInfo
	}
	return nil
}

var File_messages_DetectorIPStruct_proto protoreflect.FileDescriptor

var file_messages_DetectorIPStruct_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x50, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2f, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x10, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x50, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x2c,
	0x0a, 0x02, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02, 0x49, 0x50, 0x12, 0x40, 0x0a, 0x0d,
	0x49, 0x73, 0x49, 0x4e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x0d, 0x49, 0x73, 0x49, 0x4e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x37,
	0x0a, 0x0a, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x0a, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6f, 0x62, 0x6a, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_messages_DetectorIPStruct_proto_rawDescOnce sync.Once
	file_messages_DetectorIPStruct_proto_rawDescData = file_messages_DetectorIPStruct_proto_rawDesc
)

func file_messages_DetectorIPStruct_proto_rawDescGZIP() []byte {
	file_messages_DetectorIPStruct_proto_rawDescOnce.Do(func() {
		file_messages_DetectorIPStruct_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_DetectorIPStruct_proto_rawDescData)
	})
	return file_messages_DetectorIPStruct_proto_rawDescData
}

var file_messages_DetectorIPStruct_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messages_DetectorIPStruct_proto_goTypes = []interface{}{
	(*DetectorIPStruct)(nil),       // 0: msg.DetectorIPStruct
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 2: google.protobuf.BoolValue
	(*RegionInfoDetected)(nil),     // 3: msg.RegionInfoDetected
}
var file_messages_DetectorIPStruct_proto_depIdxs = []int32{
	1, // 0: msg.DetectorIPStruct.IP:type_name -> google.protobuf.StringValue
	2, // 1: msg.DetectorIPStruct.IsINBlackList:type_name -> google.protobuf.BoolValue
	3, // 2: msg.DetectorIPStruct.RegionInfo:type_name -> msg.RegionInfoDetected
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_messages_DetectorIPStruct_proto_init() }
func file_messages_DetectorIPStruct_proto_init() {
	if File_messages_DetectorIPStruct_proto != nil {
		return
	}
	file_messages_RegionInfoDetected_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messages_DetectorIPStruct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectorIPStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_DetectorIPStruct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_DetectorIPStruct_proto_goTypes,
		DependencyIndexes: file_messages_DetectorIPStruct_proto_depIdxs,
		MessageInfos:      file_messages_DetectorIPStruct_proto_msgTypes,
	}.Build()
	File_messages_DetectorIPStruct_proto = out.File
	file_messages_DetectorIPStruct_proto_rawDesc = nil
	file_messages_DetectorIPStruct_proto_goTypes = nil
	file_messages_DetectorIPStruct_proto_depIdxs = nil
}
