// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: enums/TypeAuth.proto

package protoobj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeAuth int32

const (
	TypeAuth_TypeAuth_NULL       TypeAuth = 0
	TypeAuth_TypeAuth_telegram   TypeAuth = 1
	TypeAuth_TypeAuth_token_auth TypeAuth = 2
	TypeAuth_TypeAuth_email_auth TypeAuth = 3
	TypeAuth_TypeAuth_vk         TypeAuth = 4
	TypeAuth_TypeAuth_password   TypeAuth = 5
)

// Enum value maps for TypeAuth.
var (
	TypeAuth_name = map[int32]string{
		0: "TypeAuth_NULL",
		1: "TypeAuth_telegram",
		2: "TypeAuth_token_auth",
		3: "TypeAuth_email_auth",
		4: "TypeAuth_vk",
		5: "TypeAuth_password",
	}
	TypeAuth_value = map[string]int32{
		"TypeAuth_NULL":       0,
		"TypeAuth_telegram":   1,
		"TypeAuth_token_auth": 2,
		"TypeAuth_email_auth": 3,
		"TypeAuth_vk":         4,
		"TypeAuth_password":   5,
	}
)

func (x TypeAuth) Enum() *TypeAuth {
	p := new(TypeAuth)
	*p = x
	return p
}

func (x TypeAuth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeAuth) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_TypeAuth_proto_enumTypes[0].Descriptor()
}

func (TypeAuth) Type() protoreflect.EnumType {
	return &file_enums_TypeAuth_proto_enumTypes[0]
}

func (x TypeAuth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeAuth.Descriptor instead.
func (TypeAuth) EnumDescriptor() ([]byte, []int) {
	return file_enums_TypeAuth_proto_rawDescGZIP(), []int{0}
}

var File_enums_TypeAuth_proto protoreflect.FileDescriptor

var file_enums_TypeAuth_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x8e, 0x01, 0x0a, 0x08,
	0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x79, 0x70, 0x65,
	0x41, 0x75, 0x74, 0x68, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x54,
	0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x54,
	0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x75,
	0x74, 0x68, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x5f, 0x76, 0x6b, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74,
	0x68, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0x05, 0x42, 0x12, 0x5a, 0x10,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6f, 0x62, 0x6a,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enums_TypeAuth_proto_rawDescOnce sync.Once
	file_enums_TypeAuth_proto_rawDescData = file_enums_TypeAuth_proto_rawDesc
)

func file_enums_TypeAuth_proto_rawDescGZIP() []byte {
	file_enums_TypeAuth_proto_rawDescOnce.Do(func() {
		file_enums_TypeAuth_proto_rawDescData = protoimpl.X.CompressGZIP(file_enums_TypeAuth_proto_rawDescData)
	})
	return file_enums_TypeAuth_proto_rawDescData
}

var file_enums_TypeAuth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_TypeAuth_proto_goTypes = []interface{}{
	(TypeAuth)(0), // 0: msg.TypeAuth
}
var file_enums_TypeAuth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_TypeAuth_proto_init() }
func file_enums_TypeAuth_proto_init() {
	if File_enums_TypeAuth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enums_TypeAuth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_TypeAuth_proto_goTypes,
		DependencyIndexes: file_enums_TypeAuth_proto_depIdxs,
		EnumInfos:         file_enums_TypeAuth_proto_enumTypes,
	}.Build()
	File_enums_TypeAuth_proto = out.File
	file_enums_TypeAuth_proto_rawDesc = nil
	file_enums_TypeAuth_proto_goTypes = nil
	file_enums_TypeAuth_proto_depIdxs = nil
}
