// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: messages/UpdateUserAvatarURLReq.proto

package protoobj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserAvatarURLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSystemID *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=userSystemID,proto3" json:"userSystemID,omitempty"`
	AvatarURL    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=avatarURL,proto3" json:"avatarURL,omitempty"`
}

func (x *UpdateUserAvatarURLReq) Reset() {
	*x = UpdateUserAvatarURLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_UpdateUserAvatarURLReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserAvatarURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAvatarURLReq) ProtoMessage() {}

func (x *UpdateUserAvatarURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_UpdateUserAvatarURLReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAvatarURLReq.ProtoReflect.Descriptor instead.
func (*UpdateUserAvatarURLReq) Descriptor() ([]byte, []int) {
	return file_messages_UpdateUserAvatarURLReq_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserAvatarURLReq) GetUserSystemID() *wrapperspb.StringValue {
	if x != nil {
		return x.UserSystemID
	}
	return nil
}

func (x *UpdateUserAvatarURLReq) GetAvatarURL() *wrapperspb.StringValue {
	if x != nil {
		return x.AvatarURL
	}
	return nil
}

var File_messages_UpdateUserAvatarURLReq_proto protoreflect.FileDescriptor

var file_messages_UpdateUserAvatarURLReq_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x40, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x3a, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x55, 0x52, 0x4c, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6f, 0x62, 0x6a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_messages_UpdateUserAvatarURLReq_proto_rawDescOnce sync.Once
	file_messages_UpdateUserAvatarURLReq_proto_rawDescData = file_messages_UpdateUserAvatarURLReq_proto_rawDesc
)

func file_messages_UpdateUserAvatarURLReq_proto_rawDescGZIP() []byte {
	file_messages_UpdateUserAvatarURLReq_proto_rawDescOnce.Do(func() {
		file_messages_UpdateUserAvatarURLReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_UpdateUserAvatarURLReq_proto_rawDescData)
	})
	return file_messages_UpdateUserAvatarURLReq_proto_rawDescData
}

var file_messages_UpdateUserAvatarURLReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messages_UpdateUserAvatarURLReq_proto_goTypes = []interface{}{
	(*UpdateUserAvatarURLReq)(nil), // 0: msg.UpdateUserAvatarURLReq
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
}
var file_messages_UpdateUserAvatarURLReq_proto_depIdxs = []int32{
	1, // 0: msg.UpdateUserAvatarURLReq.userSystemID:type_name -> google.protobuf.StringValue
	1, // 1: msg.UpdateUserAvatarURLReq.avatarURL:type_name -> google.protobuf.StringValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messages_UpdateUserAvatarURLReq_proto_init() }
func file_messages_UpdateUserAvatarURLReq_proto_init() {
	if File_messages_UpdateUserAvatarURLReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_UpdateUserAvatarURLReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserAvatarURLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_UpdateUserAvatarURLReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_UpdateUserAvatarURLReq_proto_goTypes,
		DependencyIndexes: file_messages_UpdateUserAvatarURLReq_proto_depIdxs,
		MessageInfos:      file_messages_UpdateUserAvatarURLReq_proto_msgTypes,
	}.Build()
	File_messages_UpdateUserAvatarURLReq_proto = out.File
	file_messages_UpdateUserAvatarURLReq_proto_rawDesc = nil
	file_messages_UpdateUserAvatarURLReq_proto_goTypes = nil
	file_messages_UpdateUserAvatarURLReq_proto_depIdxs = nil
}
