// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: enums/UserRole.proto

package protoobj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRole - роли пользователей
type UserRole int32

const (
	UserRole_USER        UserRole = 0 // пользователь
	UserRole_ADMIN       UserRole = 1 // администратор
	UserRole_SUPER_ADMIN UserRole = 2 // супер администратор
	UserRole_SUPPORT     UserRole = 3 // поддержка
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER",
		1: "ADMIN",
		2: "SUPER_ADMIN",
		3: "SUPPORT",
	}
	UserRole_value = map[string]int32{
		"USER":        0,
		"ADMIN":       1,
		"SUPER_ADMIN": 2,
		"SUPPORT":     3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_UserRole_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_enums_UserRole_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_enums_UserRole_proto_rawDescGZIP(), []int{0}
}

var File_enums_UserRole_proto protoreflect.FileDescriptor

var file_enums_UserRole_proto_rawDesc = []byte{
	0x0a, 0x14, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x3d, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x55, 0x50, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x03, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6f, 0x62, 0x6a, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enums_UserRole_proto_rawDescOnce sync.Once
	file_enums_UserRole_proto_rawDescData = file_enums_UserRole_proto_rawDesc
)

func file_enums_UserRole_proto_rawDescGZIP() []byte {
	file_enums_UserRole_proto_rawDescOnce.Do(func() {
		file_enums_UserRole_proto_rawDescData = protoimpl.X.CompressGZIP(file_enums_UserRole_proto_rawDescData)
	})
	return file_enums_UserRole_proto_rawDescData
}

var file_enums_UserRole_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_UserRole_proto_goTypes = []interface{}{
	(UserRole)(0), // 0: msg.UserRole
}
var file_enums_UserRole_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_UserRole_proto_init() }
func file_enums_UserRole_proto_init() {
	if File_enums_UserRole_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enums_UserRole_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_UserRole_proto_goTypes,
		DependencyIndexes: file_enums_UserRole_proto_depIdxs,
		EnumInfos:         file_enums_UserRole_proto_enumTypes,
	}.Build()
	File_enums_UserRole_proto = out.File
	file_enums_UserRole_proto_rawDesc = nil
	file_enums_UserRole_proto_goTypes = nil
	file_enums_UserRole_proto_depIdxs = nil
}
